[package]
name = "ethgas"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "0.12.5" }
anyhow = "1.0.97"
reqwest = "0.12.14"
serde = "1.0.219"
serde_json = "1.0.140"
ssi-eip712 = "0.1.0"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
uuid = "1.16.0"
